apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      # initContainers:
      #   - name: wait-for-auth
      #     image: busybox
      #     command:
      #       [
      #         "sh",
      #         "-c",
      #         'until nc -z -v -w30 auth-service.default 80; do echo "waiting for auth-service"; sleep 5; done;',
      #       ]
      containers:
        - name: tasks
          image: minghan2000/kub-demo-tasks:latest
          env:
            - name: TASKS_FOLDER
              value: k-tasks-folder
            - name: AUTH_ADDRESS
              value: "auth-service.default"
