apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer # we want this to be external facing
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
